In [1]:
import matplotlib

[f.name for f in matplotlib.font_manager.fontManager.ttflist if f.name.startswith("N")]

['Niagara Engraved',
 'NewJumja',
 'Nirmala UI',
 'Nirmala UI',
 'New Gulim',
 'Niagara Solid',
 'NanumGothic',
 'NanumGothic',
 'Nirmala UI',
 'NanumGothic',
 'NanumGothic']

In [2]:
1.0

1.0

In [3]:
%precision 55

'%.55f'

In [4]:
%.55f

UsageError: Line magic function `%.55f` not found.


In [5]:
1.0

1.0000000000000000000000000000000000000000000000000000000

In [6]:
%precision 100

'%.100f'

In [7]:
1.0

1.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [8]:
%precision 200

'%.200f'

In [9]:
1.0

1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [10]:
0.1

0.10000000000000000555111512312578270211815834045410156250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [11]:
%precision %r

'%r'

In [12]:
0.1

0.1

In [13]:
0.1+0.2

0.30000000000000004

In [15]:
%precision 55

'%.55f'

In [16]:
0.1+0.2

0.3000000000000000444089209850062616169452667236328125000

In [17]:
0.3

0.2999999999999999888977697537484345957636833190917968750

In [18]:
%precision %r

'%r'

In [19]:
0.1+0.2 == 0.3 # 실수는 오차를 가짐. 항상 round사용.

False

In [20]:
round(0.1+0.2,3)==round(0.3,3) #round는 반올림 함.

True

In [21]:
int(3.9) == 3 # < 실수 -> 정수 > 변환의 경우, 소숫점 이하 버림.

True

In [22]:
dollar = "$"
n = 1200
print("달러("+dollar+")는 "+str(n)+"원 쯤이다",end="") #숫자를 문자열과 더하려면 str()
print("!")
print(dollar*30)

달러($)는 1200원 쯤이다!
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


In [25]:
print(""" "안녕?"
그가 나에게 인사를 건넸다.
'안녕'
나는 생각했다.
""")

 "안녕?"
그가 나에게 인사를 건넸다.
'안녕'
나는 생각했다.



In [37]:
# 문자열 형식화
f = 1200.259
print("달러(%s)는 %d원 쯤이다. 정확히는 %.2f원이다." %(dollar, n, f)) # 여러개 넣어야 할 때, %() 소괄호 사용.

달러($)는 1200원 쯤이다. 정확히는 1200.26원이다.


In [114]:
# 중첩 조건문
def exam(sex, num):
    if sex == "man":
        if num > 100:
            print("특급전사")
        elif num > 30: # if가 거짓이고, elif의 조건을 만족할 때
            print("인간의 마지노선")
        else:
            print("쓰레기")
    elif sex == "woman":
        if num > 80:
            print("특급전사")
        else:
            print("괜찮음")
    else:
        print("다시 입력해라")
        
exam("man",101)
exam("man",50)
exam("man",10)
print()
exam("woman",30)
print()
exam("wm",100)

특급전사
인간의 마지노선
쓰레기

괜찮음

다시 입력해라


In [46]:
# 함수 안에서는 함수 바깥 변수의 값을 변경할 수 없다.
# global 키워드 사용 -> 가능

z = 3
print("변경 전 전역변수 z = %d" %z)
def f1(x):
    global z
    z = x + z
    return z

print("f1(3) = %d" %f1(3))
print("변경 후 전역변수 z = %d" %z)

변경 전 전역변수 z = 3
f1(3) = 6
변경 후 전역변수 z = 6


In [113]:
n=17

for i in range(n):
    if i<n//2+1:
        for j in range(i): # 1씩 증가하며 " "
            print(" ",end="")
        for k in range(n-2*i): # 2개씩 감소하며 "*"
            print("*",end="")
        print()
     
    else: # (i > 절반) 경우
        for l in range(n-i-1): # 전체 - i
            print(" ",end="")
        for m in range(2*(i-n//2)+1): # 2*(i-절반) +1
            print("*",end="")
        print()

*****************
 ***************
  *************
   ***********
    *********
     *******
      *****
       ***
        *
       ***
      *****
     *******
    *********
   ***********
  *************
 ***************
*****************


In [66]:
# 중첩 for 반복문
# 주사위를 두 번 던져서 나온 숫자들의 합이 4의 배수가 되는 경우

for i in range(6):
    for j in range(6):
        if(((i+1)+(j+1))%4==0):
            print("%d %d" %(i+1,j+1))

1 3
2 2
2 6
3 1
3 5
4 4
5 3
6 2
6 6


In [69]:
# 카운터 변수가 변하는 경우
# 1부터 1까지의 합, 1부터 2까지의 합, 1부터 3까지의 합, 이런 식으로 1부터 10까지의 합

for i in range(10):
    sol = 0
    for j in range(i+1):
        sol = sol + j + 1
    print(sol)

1
3
6
10
15
21
28
36
45
55


In [77]:
# 리스트(순서), 딕셔너리(무순서, {키:값})
# 어떤 자료형이든 가능하다.

a = [1, 3.14, "pi",[2, 3.14156]] # 리스트
d = {0 : 201523549,"math": 3.14, "english": "A+"} # 딕셔너리

print(a[1])
print(a[3][1])
print()

print(d[0])
print(d["math"])
print(d["english"])

3.14
3.14156

201523549
3.14
A+


In [104]:
# 리스트 다루기

## 수열 생성

a = list(range(1,15,3)) # list형변환 --> 명시적으로 리스트로 바꿈
a

[1, 4, 7, 10, 13]

In [117]:
# 리스트 추가/삭제

a.append(15) # append() 매서드(변수에 .(점)으로 명령): 변수에 자료 추가
print(a) 

del a[5]
print(a)

# 슬라이싱

print()
print(a[1:2])
print(a[0:3]) 
print(a[0:]) # 전체

# 음수 인덱싱: 뒤에서부터 가리킴

print()
print(a[-1])
print(a[-3:]) # -3 이후 전체

# 원소 존재 판단

7 in a 

[1, 4, 7, 10, 13, 15]
[1, 4, 7, 10, 13]

[4]
[1, 4, 7]
[1, 4, 7, 10, 13]

13
[7, 10, 13]


True

In [122]:
# 반복문에서 리스트의 원소를 뽑을 수 있음
# range 명령은 사실 리스트를 만드는 명령

a = [90, 85, 95, 80, 90, 100, 85, 75, 85, 80]

total = 0
for i in a:
    total = total+i
avg = total/len(a)
print(avg)

86.5


[185, 175, 185, 170, 185, 200, 175, 155, 180, 170]

In [131]:
# zip함수

s = []
a = [90, 85, 95, 80, 90, 100, 85, 75, 85, 80]
b = [95, 90, 90, 90, 95, 100, 90, 80, 95, 90]

print(list(zip(a,b))) # 리스트 2개 합침. 각 원소의 쌍을 튜플(tuple)로.
print()

for i, j in zip(a, b): # 리스트 내 튜플에서 원소 직접 뽑음
    s.append(i + j) 
print(s)

[(90, 95), (85, 90), (95, 90), (80, 90), (90, 95), (100, 100), (85, 90), (75, 80), (85, 95), (80, 90)]

[185, 175, 185, 170, 185, 200, 175, 155, 180, 170]


In [151]:
# enumerate함수

for i, j in enumerate(["a", "b", "c"]): # 인덱스 i 자동 생성
    print("i = %d, j = %s" % (i, j))


i = 0, j = a
i = 1, j = b
i = 2, j = c


In [153]:
# 딕셔너리 추가/삭제 

x={"a":10, "b":20} # key --> 딕셔너리 인덱싱 

x["c"]=30 # 추가
print(x)

del x["c"] # 삭제
print(x)

# 키 존재 판단

'a' in x

{'a': 10, 'b': 20, 'c': 30}
{'a': 10, 'b': 20}


True

In [167]:
# 딕셔너리 반복문

# 1. 키 반복
for i in x.keys(): # 리스트 반환
    print(i, end=" ")
print(); print()

# 2. 값 반복
for j in x.values(): # 리스트 반환
    print(j, end=" ")
print(); print()

# 3. item 반복
for k in x.items(): # 튜플 반환
    print(k, end=" ")
    print(k[0], k[1])
print()

for k,l in x.items():
    print(k,l)

a b 

10 20 

('a', 10) a 10
('b', 20) b 20

a 10
b 20


In [11]:
# 객체: 데이터(멤버) + 함수(함수)

class Renctangle:
    
    # self 매개변수 <-- 모든 메서드의 첫번째 매개변수 
    #                   객체가 자동 전달 됨(파이썬만의 특징)
    
    def __init__(self, h, v): # 생성자 (객체 생성 시 자동 호출)
        self.h = h # 객체에 변수 생성 & 저장
        self.v = v
    
    def area(self):
        return self.h * self.v
    
r = Renctangle(10, 20)
a = r.area() # 객체를 통해 메서드 호출
print(a)

200


In [41]:
# 객체: 데이터(멤버) + 함수(함수)

# self 매개변수 <-- 모든 메서드의 첫번째 매개변수 
#                   객체가 자동 전달 됨(파이썬만의 특징)

# 파이썬에는 오버로딩 없음 (동일 메소드 다른 매개변수)

class cal:
    
    name = "계산기"                # 클래스 변수는 모든 객체에 공유
    
    def __init__(self, a, b):      # 생성자 (객체 생성 시 자동 호출)
        self.a = a                 # 객체에 변수 생성 & 저장
        self.b = b
    
    def add(self):
        result = self.a + self.b
        return result
    
    def sub(self):
        result = self.a - self.b
        return result
    
    def div(self):
        result = self.a / self.b
        return result

class pow_cal(cal):                # cal 클래스 상속 (클래스 기능 확장)
    
    def div(self):                 # 오버라이딩 (동일한 이름으로 메서드 재정의)
        if (self.b == 0):
            return "*** 0으로 나눌 수 없습니다 ***"
        else:
            result = self.a / self.b
            return result
    
    def pow(self):                 # 기능 확장
        result = self.a ** self.b
        return result
    
    

In [42]:
a = cal(0, 4)
print(a.name)  # 클래스 변수는 모든 객체에 공유
print(a.div()) # 객체를 통해 메서드 호출
print()

b = pow_cal(4, 0) #  부모클래스의 메서드 대신 오버라이딩한 메서드가 호출
print(b.div())
print(b.pow())



계산기
0.0

*** 0으로 나눌 수 없습니다 ***
1


In [43]:
# 클래스 이름 앞의 __main__은 클래스가 정의된 모듈(파일 이름)
# REPL 환경에서 입력하는 코드는 __main__으로 가정

type(a)

__main__.cal

In [44]:
# 인코딩: 문자를 2진 숫자의 열(바이트 열)로 바꾸어 저장
# 유니코드: 모든 세계의 각 글자에 숫자를 지정하는 방식 (A를 65에 배당)
# 유니코드 인코딩(UTF-8 등): 유니코드 숫자를 저장하는 방식 (65를 2진수로)

# 유니코드 -> 바이트열 : 인코드
# 바이트열 -> 유니코드 : 디코드

# 파이썬에서 문자열의 자료형: 유니코드, 자료형 이름: str

In [61]:
# 파이썬에서 날짜/시간

# datetime 패키지
# 클래스: datetime(날짜,시간), date(날짜), time(시간), timedelta(날짜구간)

import datetime

datetime.datetime.now() # datetime.datetime 클래스 객체
print(datetime.datetime.now().strftime("%Y %m %d %H %M %B %A") )# strftime() : 날짜/시간 정보를 문자열로

# dateutil 패키지

from dateutil.parser import parse

# dateutil 패키지의 parse 명령을 쓰면 
# 자동으로 형식 문자열을 찾아 datetime.datetime 클래스 객체를 만들어 준다.
parse("Apr 16, 2016 04:05:32 PM")


2020 04 17 18 47 April Friday


datetime.datetime(2016, 4, 16, 16, 5, 32)

In [64]:
# NumPy 배열

# 배열: 1. 모든 원소가 같은 자료형 2. 원소의 갯수 고정
# 배열은 적은 메모리로 빠르게 데이터 처리.

import numpy as np

ar = np.array(range(10)) # 리스트 넣으면 배열로 변환
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# ndarrray(N-Dimensional array) 자료형

type(ar)

numpy.ndarray

In [75]:
# 벡터 연산: 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리

# 벡터의 덧셈

a = [1,2,3]
b = [10,20,30]
print("list:", a + b)

x = np.array(a)
y = np.array(b)
print("array:", x + y)

list: [1, 2, 3, 10, 20, 30]
array: [11 22 33]


In [6]:
# 벡터의 스칼라곱

data = [0,1,2,3,4,5]
print("list:", 2 * data)

x = np.array(data)
print("array:", 2 * x)

list: [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
array: [ 0  2  4  6  8 10]


In [95]:
# 2차원 배열

c = np.array([[0,1,2], [3,4,5]]) # 2 X 3 행렬

print(c); print()

print("행:", len(c))
print("열:", len(c[0])); print()

print("차원:", c.ndim) # ndim: 배열 속성
print("크기:", c.shape)

[[0 1 2]
 [3 4 5]]

행: 2
열: 3

차원: 2
크기: (2, 3)


In [101]:
# 3차원 배열

d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print(d); print()

print("행:", len(d))
print("열:", len(d[0]))
print("깊이:", len(d[0][0])); print()

print("차원:", d.ndim) # ndim: 배열 속성
print("크기:", d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

행: 2
열: 3
깊이: 4

차원: 3
크기: (2, 3, 4)


In [106]:
# 배열 슬라이싱

a = np.array([[0,1,2,3], [4,5,6,7]])
print(a); print()

# 1행
print(a[0, :])
print()

# 2열
print(a[:, 1])
print()

# 2 x 2
print(a[:2, :2])
print()

# 2행의 2번째 열부터 전부
print(a[1, 1:])

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3]

[1 5]

[[0 1]
 [4 5]]

[5 6 7]


In [27]:
# 불리안/정수 배열 인덱싱

a = np.array([0,1,2,3,4,5,6,7,8,9])

# 불리안 배열 인덱싱 (객체의 크기와 같아야 함)

print("a % 2 =", a % 2) # 짝수인 원소
print("a[a % 2 == 0] =", a[a % 2 == 0])
print()

# 정수 배열 인덱싱 (객체의 크기와 달라도 됨)

a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
i = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
print(a[i]); print()

# 다차원 배열 인덱싱
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print()

# 전체에서 1, 4 열
print(a[:, [True, False, False, True]])
print()

print(a[:, [0,3]])
print()

# 3행, 1행, 2행 순으로 행렬 바꾸기
print(a[[2, 0, 1], :])

a % 2 = [0 1 0 1 0 1 0 1 0 1]
a[a % 2 == 0] = [0 2 4 6 8]

[11 11 11 11 11 11 22 22 22 22 22 33 33 33 33 33]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [29]:
# 배열 자료형: 자료형을 명시하지 않으면 스스로 유추

x = np.array([1, 2, 3.0])
print(x[0])

# 무한대 np.inf


1.0
